create table if not exists public.anonymous_messages (
  anon_id bigint generated by default as identity primary key,
  telegram_message_id bigint not null,
  admin_message_id bigint,
  target_user_id bigint not null default 0,
  user_id bigint not null,
  username text not null default '',
  name text not null,
  kind text not null,
  text text not null default '',
  created_at text not null,
  raw jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now()
);

drop index if exists public.anonymous_messages_telegram_message_id_key;

create unique index if not exists anonymous_messages_user_message_id_key
  on public.anonymous_messages (user_id, telegram_message_id);

create index if not exists anonymous_messages_admin_message_id_idx
  on public.anonymous_messages (admin_message_id);

create index if not exists anonymous_messages_user_id_idx
  on public.anonymous_messages (user_id);

create index if not exists anonymous_messages_target_user_id_idx
  on public.anonymous_messages (target_user_id);

create table if not exists public.anon_sessions (
  chat_id bigint primary key,
  target_user_id bigint not null,
  updated_at timestamptz not null default now()
);

create index if not exists anon_sessions_target_user_id_idx
  on public.anon_sessions (target_user_id);

create table if not exists public.anon_profiles (
  user_id bigint primary key,
  username text not null default '',
  profile_link text not null,
  updated_at timestamptz not null default now()
);

create unique index if not exists anon_profiles_user_id_key
  on public.anon_profiles (user_id);

alter table public.anonymous_messages enable row level security;
alter table public.anon_sessions enable row level security;
alter table public.anon_profiles enable row level security;

drop policy if exists "service role full access" on public.anonymous_messages;
create policy "service role full access"
  on public.anonymous_messages
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists "service role full access" on public.anon_sessions;
create policy "service role full access"
  on public.anon_sessions
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists "service role full access" on public.anon_profiles;
create policy "service role full access"
  on public.anon_profiles
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
